import { ArrowRight, ArrowUpRight, Check, CircleCheck, FileSearch, Fingerprint, ShieldCheck, TriangleAlert, ZoomIn } from 'lucide-react';
import { SectionHeading } from '../components/SectionHeading';
import { Reveal } from '../components/Reveal';
import results from '../data/test_results.json';

export interface EvidenceAsset { file: string; title: string; figure: string }
export interface ValidationProps { step: number; onStep: (step:number)=>void; onEvidence: (asset:EvidenceAsset)=>void }
const evidenceAsset=(file:string,title:string,figure:string):EvidenceAsset=>({file,title,figure});
const e2eAssets=[evidenceAsset('fig31.png','CloudWatch · Declaración PT','Figura 31'),evidenceAsset('fig32.png','Archivo XML en la carpeta de intercambio','Figura 32'),evidenceAsset('fig33.png','Softland · Procesamiento y cantidades iguales','Figura 33')];

function EvidenceButton({asset,onEvidence,compact=false}:{asset:EvidenceAsset;onEvidence:ValidationProps['onEvidence'];compact?:boolean}) {
  return <button className={`evidence-image ${compact?'evidence-compact':''}`} onClick={()=>onEvidence(asset)} aria-label={`Ampliar ${asset.title}`}><img src={`${import.meta.env.BASE_URL}evidence/${asset.file}`} alt={asset.title} loading="lazy"/><span><ZoomIn size={16}/>{asset.figure} · Ampliar evidencia</span></button>;
}

const controls=[
  {title:'Validación',icon:ShieldCheck,kicker:'ANTES DE TRANSFORMAR',description:'Comprobar estructura, campos obligatorios y reglas del movimiento.',example:'SKU · OT · Fechas · Bodega · Unidad de medida',result:'Un dato inválido debe quedar identificado antes de producir un movimiento incorrecto.'},
  {title:'Idempotencia',icon:Fingerprint,kicker:'ANTE UN REENVÍO',description:'Identificar eventos ya procesados y evitar un segundo movimiento.',example:'Identificador natural → control de duplicidad',result:'El reenvío se detecta y se ignora.',asset:evidenceAsset('fig40.png','Reenvío de PT detectado e ignorado','Figura 40')},
  {title:'Errores y reproceso',icon:TriangleAlert,kicker:'CUANDO ALGO FALLA',description:'Detener, aislar y conservar el motivo para un reproceso controlado.',example:'Error técnico ≠ rechazo de negocio',result:'Un XML válido puede ser rechazado por stock o reglas internas de Softland.',asset:evidenceAsset('fig37.png','Softland rechaza el movimiento por stock','Figura 37')},
  {title:'Trazabilidad',icon:FileSearch,kicker:'HASTA EL DESTINO',description:'Relacionar el evento, la ejecución, el archivo y el resultado final.',example:'CloudWatch → XML → intercambio → Softland',result:'Una ejecución exitosa en Lambda no basta para confirmar la transacción en ERP.',asset:e2eAssets[0]},
];

export function EngineeringControls({step,onStep,onEvidence}:ValidationProps) {
  const item=controls[step]; const Icon=item.icon;
  return <div className="section-inner validation-section"><SectionHeading number="09" label="CONTROLES DE INGENIERÍA">Transformar formatos<br/><span>es solo una parte.</span></SectionHeading><div className="control-layout"><div className="control-menu">{controls.map(({title,icon:ControlIcon},i)=><button key={title} aria-pressed={step===i} onClick={()=>onStep(i)}><span>0{i+1}</span><ControlIcon/><strong>{title}</strong><ArrowUpRight size={18}/></button>)}</div><div className="control-detail" key={step}><p className="eyebrow"><Icon size={19}/>{item.kicker}</p><h3>{item.description}</h3><p className="control-example">{item.example}</p><p>{item.result}</p>{item.asset&&<button className="text-button" onClick={()=>onEvidence(item.asset!)}>Ver evidencia real <ZoomIn size={18}/></button>}</div></div><p className="source-note">FUENTE · Informe final, controles de idempotencia y errores; figuras 35–40.</p></div>;
}

const testingStages=['Funcionales','Transformación','Integración','Extremo a extremo','Reconciliación','Duplicidad y error','Rendimiento / resiliencia','Piloto productivo'];
const testingNotes=[
  'Comprobar el comportamiento de cada función de forma aislada.',
  'Verificar los contratos y la transformación entre XML y JSON.',
  'Comprobar el intercambio entre los componentes de la integración.',
  'Seguir el flujo completo y comprobar el procesamiento en el sistema destino.',
  'Comparar las cantidades y referencias de origen con las registradas en destino.',
  'Provocar condiciones de duplicidad y error; comprobar el control de reproceso.',
  'Evaluar cargas representativas y ajustar la operación ante fallas y límites.',
  'Validar con datos reales y monitorear la estabilización de los flujos.',
];
export function Testing({step}:ValidationProps) {
  const reached=step;
  return <div className="section-inner validation-section"><SectionHeading number="10" label="ESTRATEGIA DE PRUEBAS">De la función aislada<br/><span>a la operación real.</span></SectionHeading><div className="testing-pipeline">{testingStages.map((s,i)=><div className={`${i<=reached?'reached':''} ${i===reached?'current':''}`} aria-current={i===reached?'step':undefined} key={s}><span>{String(i+1).padStart(2,'0')}</span><strong>{s}</strong>{i<=reached?<Check size={19}/>:<ArrowRight size={19}/>}</div>)}</div><div className="active-explanation"><span><ShieldCheck/></span><p>{testingNotes[step]}</p></div><Reveal show={step>=6} className="test-volume"><div><p className="eyebrow">CARGA REPRESENTATIVA DEL TT</p><p>Eventos aproximados evaluados</p></div>{results.volumes.map(v=><div key={v.flow}><strong>≈{v.approx_events}</strong><span>{v.flow.replace(' multi-línea','').replace(' Softland → Invas','')}</span></div>)}</Reveal><p className="methodology">Validación operacional con cargas representativas; no fue un benchmark formal de alto volumen.</p><p className="source-note">FUENTE · Informe final, capítulo 8 y anexos de rendimiento y resiliencia.</p></div>;
}

const evidenceNarrative=[{title:'El evento se transforma.',detail:'CloudWatch identifica DECLARAPT, OT-10264 y el SKU 101006 con 120 unidades.',key:'Evento y ejecución'},{title:'El archivo queda disponible.',detail:'El XML de esa declaración aparece en la ruta de intercambio de archivos.',key:'Documento de intercambio'},{title:'Softland confirma el movimiento.',detail:'Los logs de destino muestran guía creada y 120 movimientos enviados / creados: cantidades iguales.',key:'Resultado en destino'},{title:'La cantidad se conserva.',detail:'El evento de origen y el procesamiento de Softland coinciden para el caso documentado.',key:'Reconciliación'}];
export function Evidence({step,onStep,onEvidence}:ValidationProps) {
  const narrative=evidenceNarrative[step];
  return <div className="section-inner validation-section evidence-section"><SectionHeading number="11" label="EVIDENCIA E2E">La prueba está<br/><span>en el destino.</span></SectionHeading><div className="evidence-stages">{evidenceNarrative.map((n,i)=><button key={n.key} onClick={()=>onStep(i)} aria-pressed={step===i}><span>{i+1}</span>{n.key}</button>)}</div><div className="evidence-layout"><div className="evidence-main">{step<3?<EvidenceButton asset={e2eAssets[step]} onEvidence={onEvidence}/>:<div className="reconciliation-proof"><EvidenceButton asset={e2eAssets[0]} onEvidence={onEvidence} compact/><EvidenceButton asset={e2eAssets[2]} onEvidence={onEvidence} compact/></div>}</div><div className="evidence-reading"><p className="eyebrow">CASO DOCUMENTADO · PT</p><h3>{narrative.title}</h3><p>{narrative.detail}</p><div className="reconciled-number"><strong>120</strong><span>unidades · SKU 101006</span>{step>=2&&<span className="proof-success"><CircleCheck size={17}/>Conciliado</span>}</div></div></div><p className="source-note">FUENTE · Informe final, figuras 31–34 y tabla 100. Capturas originales; la figura 34 compara las evidencias de origen y destino.</p></div>;
}

const pilotNames=['QA','Validación','Despliegue','Piloto','Monitoreo','Ajustes','Estabilización'];
export function Pilot({step,onEvidence}:ValidationProps) {
  const reached=step;const asset=[evidenceAsset('fig18.png','Piloto · Consumos procesados en Softland','Figura 18'),evidenceAsset('fig19.png','Piloto · Declaración PT en CloudWatch','Figura 19'),evidenceAsset('fig20.png','Piloto · Archivos procesados','Figura 20')][step<3?0:step<5?1:2];
  return <div className="section-inner validation-section"><SectionHeading number="12" label="PILOTO Y ESTABILIZACIÓN">De QA<br/><span>a datos reales.</span></SectionHeading><div className="pilot-timeline">{pilotNames.map((n,i)=><div className={`${i<=reached?'reached':''} ${i===reached?'current':''}`} aria-current={i===reached?'step':undefined} key={n}><i/><span>{n}</span></div>)}</div><div className="pilot-layout"><div><p className="eyebrow">ACTIVACIÓN CONTROLADA</p><h3>{['Comprobar en QA.','Validar antes de activar.','Desplegar la integración.','Observar el flujo real.','Monitorear las ejecuciones.','Detectar y ajustar.','Confirmar la viabilidad operacional.'][step]}</h3><p>Monitoreo de ejecuciones, archivos y resultados en Softland.</p><div className="error-distinction"><span>Error técnico</span><strong>≠</strong><span>Rechazo de negocio</span></div><p className="technical-note">Stock insuficiente, datos maestros y reglas internas requieren una respuesta operacional.</p></div><EvidenceButton asset={asset} onEvidence={onEvidence}/></div><p className="source-note">FUENTE · Informe final, capítulo 9, figuras 18–20. Evidencia del piloto; no es una conexión al entorno productivo.</p></div>;
}

const comparison=[['Doble digitación','Sincronización en flujos integrados'],['Intercambio manual','Transformación XML / JSON'],['Duplicidad difícil de controlar','Identificadores e idempotencia'],['Error difícil de localizar','Trazabilidad y rutas de error']];
export function Results({step}:ValidationProps) {
  return <div className="section-inner validation-section"><SectionHeading number="13" label="RESULTADOS">Menos trabajo manual.<br/><span>Más control del intercambio.</span></SectionHeading><div className="results-layout"><div className="results-comparison"><div className="comparison-head"><span>AS-IS</span><span>TO-BE</span></div>{comparison.map(([a,b])=><div className="comparison-row" key={a}><span>{a}</span><ArrowRight size={18}/><strong>{b}</strong></div>)}</div><div className="result-metric"><p className="eyebrow">{['CAMBIO OBSERVADO','PROCESAMIENTO AWS','PROCESAMIENTO SOFTLAND','REFERENCIA OPERACIONAL'][step]}</p><strong>{['Conectados','1–2 s','≈10','30–60'][step]}</strong><span>{['Flujos integrados y trazables','Clasificación, transformación y archivo','archivos por minuto observados','minutos antes'][step]}</span>{step===3&&<div className="metric-after"><ArrowRight/><strong>≈≤5 min</strong><span>después</span></div>}<p>{['La integración reduce la dependencia de replicar registros manualmente.','En los casos analizados de Declarar PT y Consumir MP, según logs. No representa toda la latencia E2E.','Ritmo variable según tamaño y complejidad del XML. La lectura posterior del ERP aporta variabilidad.','Estimación operacional del informe; no medición instrumentada ni SLA.'][step]}</p></div></div><div className="result-boundary"><TriangleAlert size={19}/><p>La integración no elimina por sí sola diferencias históricas, stock insuficiente ni problemas de datos maestros.</p></div><p className="source-note">FUENTE · Informe final, resumen, capítulos 8–9 y observaciones de rendimiento. No se calculan porcentajes de mejora no medidos.</p></div>;
}

export function Conclusions({step}:ValidationProps) {
  return <div className="section-inner validation-section"><SectionHeading number="14" label="CONCLUSIONES">Interoperabilidad viable.<br/><span>Con límites explícitos.</span></SectionHeading><div className="conclusion-list"><div><span>01</span><p><strong>Viabilidad técnica y operacional.</strong> Middleware bidireccional validado mediante pruebas y piloto.</p></div><div><span>02</span><p><strong>Menor dependencia del registro manual.</strong> Transformación, validación, idempotencia y trazabilidad en los flujos integrados.</p></div><Reveal show={step>=1}><span>03</span><p><strong>La calidad del dato sigue importando.</strong> Ante un problema externo, la solución ayuda a detectar, aislar y conservar evidencia.</p></Reveal></div><Reveal show={step>=2} className="future-work"><p className="eyebrow">TRABAJO FUTURO · EVOLUCIÓN PROPUESTA</p><div><span>Regresión automatizada</span><span>CI/CD de Lambdas</span><span>Reproceso asistido</span><span>Observabilidad</span></div><p>Mayor desacoplamiento si el volumen y la criticidad lo justifican.</p></Reveal><p className="source-note">FUENTE · Informe final, capítulo 10. Las mejoras futuras no se presentan como implementación concluida.</p></div>;
}

export const additionalEvidence:EvidenceAsset[]=[evidenceAsset('fig35.png','Clasificación del evento en CloudWatch','Figura 35'),evidenceAsset('fig36.png','Archivo aislado en Errors','Figura 36'),evidenceAsset('fig37.png','Rechazo por stock en Softland','Figura 37'),evidenceAsset('fig38.png','Procesamiento original de la declaración','Figura 38'),evidenceAsset('fig39.png','Reenvío desde el registro ERP','Figura 39'),evidenceAsset('fig40.png','Duplicado detectado e ignorado','Figura 40')];
